### ISSUE TITLE
Using `export default commander `

### ISSUE THREAD

**Issue by joe223** [tj/commander.js#879] opened 2018-10-15 06:13 UTC
how about using `export default commander` instead of
https://github.com/tj/commander.js/blob/700130ee5db09d1529e89dbce74709d215640fed/typings/index.d.ts#L309

Commander is a great library :)

**Comment by vanesyan** [comment] 2018-10-24 18:32
@alan-agius4 can you please resolve it?

**Comment by alan-agius4** [comment] 2018-10-24 18:40
Sure thing, I’ll look into this tmr or Friday probably.

**Comment by alan-agius4** [comment] 2018-10-25 07:54
I had a look at this, and this is not solely typings related commander doesn't have a default export.

Commander exports a static Commander, thus using `export default` in the typings is incorrect and will make the usages of commander not work.

Take a look a what `require('commander') returns
```
Command {
  commands: [],
  options: [],
  _execs: {},
  _allowUnknownOption: false,
  _args: [],
  _name: '',
  Command:
   { [Function: Command]
     super_:
      { [Function: EventEmitter]
        EventEmitter: [Circular],
        usingDomains: false,
        defaultMaxListeners: [Getter/Setter],
        init: [Function],
        listenerCount: [Function] } },
  Option: [Function: Option] }
```

Thus, this is the correct implementation.

**Comment by vanesyan** [comment] 2018-10-25 09:36
Thanks a lot. I'll close it as resolved, feel free to reopen it if you think the issue is closed incorrectly

**Closed by vanesyan** 2018-10-25 09:36 UTC

**Comment by joe223** [comment] 2018-10-29 16:19
Thanks. `export default` can not be used due to the using of:
https://github.com/tj/commander.js/blob/27aeac1c2d3a81977592f4b772b8b9f7a6b7560d/index.js#L28

Is my understanding correct？

**Comment by joe223** [comment] 2018-10-30 07:03
I got it! Thank you so much.
