### ISSUE TITLE
passThroughOptions with command

### ISSUE THREAD

**Issue by nidhi-tandon** [tj/commander.js#1461] opened 2021-02-03 10:26 UTC
Trying to use `passThroughOptions` with `command`

Code:
```
program.enablePositionalOptions();

program
  .command('prettier')
  .description('runs prettier')
  .passThroughOptions()
  .action((env, options) => {
    console.log(`Running: ${options.args.join(' ')}`);
  });

program.parse();
```
Using as 
`node <path_to_file> prettier --write .` 

Error 
`error: unknown option '--write'`

What's working 
`node <path_to_file> prettier -- --write .`

Output:
`Running: prettier -- --write .`

`--` should not be required to make it work as passThroughOptions is used

References used: https://github.com/tj/commander.js/blob/master/examples/pass-through-options.js 
https://github.com/tj/commander.js/blob/master/examples/positional-options.js

**Comment by shadowspawn** [comment] 2021-02-03 10:49
Good description, thanks.

This is intended behaviour, but is a little subtle. `. passThroughOptions()` means the options after the first command-argument are ignored. The options before the first command-argument are processed as normal, so the subcommand can still have its own options. Your use case does not  have a command-argument for `prettier` so the option is getting processed.

The work-around is to also specify `.allowUnknownOption()`. This suppresses the error and effectively turns the unknown option into a command-argument. I think this will give you the behaviour you want.

(If that is unclear, I can write some examples. It is late here so I am doing a quick reply!)

**Comment by nidhi-tandon** [comment] 2021-02-03 12:05
Will be better if you can give some examples. Also in [this](https://github.com/tj/commander.js/blob/master/examples/pass-through-options.js) example, you are using `arguments` and in the above code, I am using `command`.

**Comment by shadowspawn** [comment] 2021-02-04 00:24
I will post some more examples here for comment.

**Comment by shadowspawn** [comment] 2021-02-04 10:51
If your subcommand does not have any of your own options, you could just allow unknown options:

```js
const { program } = require('commander');

program.enablePositionalOptions();

program
  .command('prettier')
  .description('runs prettier')
  .allowUnknownOption()
  .action((env, options) => {
    console.log(`Running: ${options.args.join(' ')}`);
  });

program.parse();
```

```
% node simple.js prettier --write .
Running: --write .
% node simple.js prettier foo      
Running: foo
```

**Comment by shadowspawn** [comment] 2021-02-04 11:01
If your subcommand may have your own options at the start of the arguments, you can use `.allowUnknownOption()` and `.passThroughOptions()`:

```js
const { program } = require('commander');

program.enablePositionalOptions();

program
  .command('prettier')
  .description('runs prettier')
  .option('-p, --prompt <value>', )
  .passThroughOptions()
  .allowUnknownOption()
  .action((options, cmd) => {
    const prompt = options.prompt || 'Running';
    console.log(`${prompt}: ${cmd.args.join(' ')}`);
  });

program.parse();
```

```
% node index.js prettier --prompt=Debugging --write . --prompt=prettier
Debugging: --write . --prompt=prettier
```

**Comment by pluqueTheLuxe** [comment] 2021-02-05 01:31
And what if I have a cli command like this: `$ cli parentCmd --dry-run subCmd <someArg>`... how would I make my `subCmd` subcommand interpret the `--dry-run` parent option?

**Comment by pluqueTheLuxe** [comment] 2021-02-05 01:59
nvm, I you answer it @ #1229

**Comment by shadowspawn** [comment] 2021-02-05 03:04
@pluqueTheLuxe
To be clear, parsing a parent option is supported but you need to access the option value yourself and it is not passed into the action handler for subCmd explicitly.

```
// assuming you have have variable for parentCmd you can access dryRun using
parentCmd.opts().dryRun
// or in subCmd action handler using command passed into handler (i.e. subCmd)
subCmd.parent.opts().dryRun
```

**Comment by shadowspawn** [comment] 2021-03-02 08:16
An answer was provided, and no further activity in a month. Closing this as resolved.

I will be watching to see if more people confused that `.passThroughOptions()` only applies after first command-argument, and whether should build up the examples.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2021-03-02 08:16 UTC
