### ISSUE TITLE
Breaks when using "domain" as an option

### ISSUE THREAD

**Issue by mgartner** [tj/commander.js#370] opened 2015-03-12 02:58 UTC
``` js
program
  .option('-d, --domain <domain>', 'domain name', 'example.com')
  .parse(process.argv);
```

```
events.js:86
    this.domain.enter();
                ^
TypeError: Object example.com has no method 'enter'
    at Command.emit (events.js:86:17)
    at Command.parseOptions (/Users/marcus/delstat/node_modules/commander/index.js:647:14)
    at Command.parse (/Users/marcus/delstat/node_modules/commander/index.js:435:21)
    at Object.<anonymous> (/Users/marcus/delstat/delstat.js:22:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by SomeKittens** [comment] 2015-03-14 19:33
Can you provide the full example?

**Comment by mgartner** [comment] 2015-03-15 17:32
```js
// test.js
'use strict';

var program = require('commander');

program
  .option('-d, --domain <domain>', 'domain name', 'example.com')
  .parse(process.argv);

console.log(program.domain);
```

```
$ node test.js -d github.com                                                        ~/commander-test

events.js:86
    this.domain.enter();
                ^
TypeError: Object example.com has no method 'enter'
    at Command.emit (events.js:86:17)
    at Command.parseOptions (/Users/marcus/commander-test/node_modules/commander/index.js:647:14)
    at Command.parse (/Users/marcus/commander-test/node_modules/commander/index.js:435:21)
    at Object.<anonymous> (/Users/marcus/commander-test/test.js:7:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by hildjj** [comment] 2015-08-28 05:28
I just ran into this too. Version 2.8.1.

**Comment by zhiyelee** [comment] 2015-08-28 13:51
yep. That's a problem, hope can fix it in v3.0, cause it will be a break change. 
https://github.com/tj/commander.js/issues/404#issuecomment-102613456 

thanks @tonylukasavage  for providing the list

**Comment by benjamine** [comment] 2016-11-08 21:18
+1

**Comment by ilyache** [comment] 2017-10-12 07:38
+1

**Comment by wolfgang42** [comment] 2017-10-30 18:30
+1, duplicate of #105.

Barring a 3.0 release, maybe trying to use `config.option('--domain')` should at least raise an error explaining the problem and offering some workaround?

**Comment by shadowspawn** [comment] 2019-04-07 05:46
The `domain` issue in particular is fixed in node 10.

**Comment by shadowspawn** [comment] 2019-04-17 22:20
Closing this as covered by #183 and #933

**Closed by shadowspawn** 2019-04-17 22:20 UTC

**Comment by shadowspawn** [comment] 2019-11-23 00:30
I have opened a Pull Request which allows storing option values separately rather than as command properties (access using `.opts()`), and passes the options (rather than the command) to the action handler. Opt-in using

```
program.configureCommand({ modern: true });
```

See #1102
