### ISSUE TITLE
option doesn't work correctly when given four arguments

### ISSUE THREAD

**Issue by tk1** [tj/commander.js#686] opened 2017-08-30 15:48 UTC
This gist https://gist.github.com/tk1/70fa2ea28b359b90eb1e0181c6cec977 demonstrates a case where the option value is completely wrong.

**Comment by vanesyan** [comment] 2017-08-30 20:53
Can you, please, test the code in previous versions of commander v2.10 and v2.9 and feedback it here, thx! We need to know was this regression introduced in newer version of commander, or exists in previous as well.

**Comment by tk1** [comment] 2017-08-31 08:17
Version 2.0.0 and 2.1.0 are correct. The error exists since version 2.2.0

**Comment by codeclown** [comment] 2017-10-24 16:03
Based on my research, this happens because the default value is passed as a second argument to the coerce function.
```js
program.option('-i, --int <n>', 'pass an int', parseInt, 100)
program.parse(['node', 'test', '-i', '5.5']);
// will invoke
parseInt('5.5', 100)
```
Obviously results in an unexpected result in case of `parseInt`.

Relevant line where coerce function is called.
https://github.com/tj/commander.js/blob/0ae835315a4ff9162c963eb2223c327fd9119996/index.js#L400

I'm willing to contribute a PR but I'm not sure what would be the best course of action to handle this.

**Comment by edemaine** [comment] 2018-07-23 16:00
For what it's worth, I've found that specifying the default *before* the transform works right:
```js
.option('-d --integer-with-default <n>', 'An integer argument with default value', 22, parseInt)
```
Whereas listing the default after the transform gets it passed in the transform:
```js
.option('-a --append <x>', 'A list argument', (x, list) => list.push(x), [])
```
So perhaps this is all intended behavior.  It's not exactly well-documented, though.

**Comment by shadowspawn** [comment] 2019-04-17 22:38
Closing as covered by #201 and #943

**Closed by shadowspawn** 2019-04-17 22:38 UTC
Labels: docs
