### ISSUE TITLE
Can not use action as option name

### ISSUE THREAD

**Issue by dehghani-mehdi** [tj/commander.js#1020] opened 2019-08-15 10:42 UTC
Hi,

Consider following code:

```
program
    .command('command <name>')
    .option("-a, --action", "Action")
    .description('Demo')
    .action((name, options) => {
        console.log(`name: ${name}`);
        console.log(`action: ${options.action}`);
    });
```

When I call it like this: `command NAME -a`, the output will be:

```
name: NAME
action: undefined
```

But when I call it like this: `command NAME -a -a`, the output will be:

```
name: NAME
action: true
```

Now if I change `.option("-a, --action", "Action")` to `.option("-a, --action_", "Action")` and `console.log(`action: ${options.action}`);` to `console.log(`action: ${options.action_}`);` and call it like this `command NAME -a`, the output will be:

```
name: NAME
action: true
```

**Comment by shadowspawn** [comment] 2019-08-15 11:13
The option values are added as properties on a Command object. This can conflict with properties which are already part of a Command, like in the case of an `action` option, the `.action` method!

This was a tradeoff in the original design. The work-around is to use a different option name.

The reference open bug is #183.

**Comment by dehghani-mehdi** [comment] 2019-08-15 12:11
I'm working on react related project and I have to use `action` as option name (_`redux's action`_) and using other name is not good for me. I think you should handle it, e.g: use something like `__action`.

**Comment by shadowspawn** [comment] 2019-08-16 00:40
Fixing the name pollution properly is hard due to existing client usage. The triage issue where I am collecting name pollution issues is #933. The draft Pull Request where I am experimenting is #951.

**Comment by dehghani-mehdi** [comment] 2019-08-16 04:12
Great.

For now I used `rawArgs` to check if `action` is provided by user.

**Comment by shadowspawn** [comment] 2019-09-14 00:04
Added to the triage issue #933
Closing as duplicate of #183 

Thank you  for your contributions.

**Closed by shadowspawn** 2019-09-14 00:04 UTC

**Comment by shadowspawn** [comment] 2019-11-23 00:25
I have opened a Pull Request which allows storing option values separately rather than as command properties (access using `.opts()`), and passes the options (rather than the command) to the action handler. Opt-in using

```
program.configureCommand({ modern: true });
```

See #1102

**Comment by shadowspawn** [comment] 2020-01-06 09:56
Added `.storeOptionsAsProperties()` and `.passCommandToAction()` in Commander 4.1. 

See: https://github.com/tj/commander.js#avoiding-option-name-clashes
