### ISSUE TITLE
how to use sub command with option?

### ISSUE THREAD

**Issue by kylelix7** [tj/commander.js#521] opened 2016-04-06 23:34 UTC
Hi I am trying sub command with option. Is there an example? I tried below code. How can I get the option value from the action callback?

```
 program
  .command('upload')
  .description('upload a file')
  .option('-f, --file <file>', 'file name')
  .action(function(file) {
    console.log("uploading...");
    console.log(file);
  });

 program.parse(process.argv);
```

$ node index.js upload -f filename
uploading...
Command {
  commands: [],
  options: 
   [ Option {
       flags: '-f, --file <file>',
       required: -12,
       optional: 0,
       bool: true,
       short: '-f',
       long: '--file',

**Comment by drewbrokke** [comment] 2016-04-07 17:44
Hi @kylelix7, the last argument passed to the callback is actually an options object so you should be able to get the file name value with options.file.
```
program
  .command('upload')
  .description('upload a file')
  .option('-f, --file <file>', 'file name')
  .action(function(options) {
    console.log("uploading...");
    console.log(options.file);
  });

program.parse(process.argv);
```

If you have arguments available to the command (as in program.command('upload' [fileName])), they will be expected arguments in the callback function. See https://www.npmjs.com/package/commander#examples. Hope this helps!

**Comment by cameronroe** [comment] 2016-08-18 20:30
What if you're using git-style commands in different files? The options don't seem to come through when chaining the `.action` cb

**Comment by gentunian** [comment] 2016-09-23 23:29
If you want git-style sub commands this is something I would do:

/var/foo/bar/main:
```javascript
#!/usr/bin/env node
'use strict';
const program = require('commander');

program
    .version('0.0.1')
    .command('create', 'command description')
    .parse(process.argv);
```

/var/foo/bar/main-create:
```javascript
#!/usr/bin/env node
'use strict';
const program = require('commander');

program
    .version('0.0.1')
    .command('cluster','command description')
    .parse(process.argv);

```

/var/foo/bar/main-create-cluster
```javascript
#!/usr/bin/env node
'use strict';
const program = require('commander');
program
    .version('0.0.1')
    .option('-n, --name <name>', 'Sets the cluster name')
    .option('-i, --ip <ip>', 'Sets the cluster ip')
    .parse(process.argv);


```

but note that `commander` won't show you help usage for options.

**Comment by dgem** [comment] 2017-02-06 14:55
Have a related question about subcommands... what if want to use common options across subcommands. Based on the above it seems I have to define them in all my subcommands. Am I missing something?

For example, I want to have a `-l --loglevel [debug|info|warn|error]` option for all my commands & subcommands. It seems I need to set a `program.option` in each top level command and all subcommands.

I guess I could have a function that takes `program` as a param, or is there a better way?

**Comment by jlison** [comment] 2017-07-18 20:44
Another solution to have multiple sub commands that seems to be working for me is to:

```javascript
// First add general program commands, as you normally would...
// For example:

// ... <blocks of code> ...
 
const program = require('commander');
program
  .command('create <type>')
  .alias('c')
  .description('parent command description..')
  .on('--help', () => { console.log('help stuff for your create command...'); });
```

```javascript
// Remove the passed parent commands, but only when sub (child) commands available.
// Add program (child) sub-commands
switch(process.argv[2]){
  case 'create':
  case 'c':
    process.argv.splice(2, 1);
    program
      .command('\tcluster <name>')
      .alias('c')
      .description('subcommand description')
      .option('-n, --name <name>', 'Sets the cluster name')
      .option('-i, --ip <ip>', 'Sets the cluster ip')
      .action((name, options) => { console.log('Name is: %s', name); })
      .on('--help', () => { console.log('help stuff for your cluster subcommand...'); });
  break;
}
```

...and finally...

```javascript
cli.parse(process.argv);
```

Any thoughts on this method? :)

**Comment by frankcchen** [comment] 2018-10-19 18:14
@gentunian Hey what if at the first level, I want to list the available sub-commands of 'main'? For example right now if I do 
`$cli-name create` 
by itself it will raise error since I don't give any sub-command.

**Comment by gentunian** [comment] 2018-10-19 19:49
@frankcchen I cannot reproduce that:

**~/code/nodejs/borrar/main.js:**
```javascript
#!/usr/bin/env node
'use strict';
const program = require('commander');

program
    .version('0.0.1')
    .command('create', 'command description')
    .parse(process.argv);
```

**~/code/nodejs/borrar/main-create.js:**
```javascript

```javascript
#!/usr/bin/env node
'use strict';
const program = require('commander');

program
    .version('0.0.1')
    .command('cluster','command description')
    .parse(process.argv);
```

**Test:**
```
[seba@leyla:~/code/nodejs/borrar] 2s $ node main.js 
Usage: main [options] [command]

Options:
  -V, --version  output the version number
  -h, --help     output usage information

Commands:
  create         command description
  help [cmd]     display help for [cmd]
[seba@leyla:~/code/nodejs/borrar] $ node main.js create
Usage: main-create [options] [command]

Options:
  -V, --version  output the version number
  -h, --help     output usage information

Commands:
  cluster        command description
  help [cmd]     display help for [cmd]

```

**Comment by frankcchen** [comment] 2018-10-22 22:21
@gentunian You're right.
What if I want to handle unsupported command at the top level aka main.js. Assume your program only has command 'create'. now if I do 
`$ node main.js bogus`
It will have no output.

I have tried adding
`.on('command:* , () => {...});`
But it didn't really work. The added line intercepts all commands basically.

**Comment by gentunian** [comment] 2018-10-22 23:31
@frankcchen I think you could try and play with the result of parsing the options/commands.

Play with this:

**/var/foo/main.js:**
```javascript
#!/usr/bin/env node
'use strict';
const program = require('commander');

const r = program
    .version('0.0.1')
    .command('create', 'command description')
    .parse(process.argv);

if (r) {
   console.log('I think no matches were found');
} else {
   console.log('possibly an error when invoking a sub-command');
}

```

**Comment by davidkjackson54** [comment] 2018-12-26 23:07
I understand the process of how Commander handles subcommands and how each level is a js file in its own right - although i think this is a very cludgy approach.   
I will have around 15 first level commands and maybe as many 10 second level commands for each of the first level command followed by optional parameters - so that is going to lead to a huge number of sub folders just to manage the process. 
for example:
job list   -prefix 
job status -jname
job purge -jname 
job submit -batchfile

in this examplej ob is a top level command category and the second command (list etc) is the action to take within that category. 
Rather than be fixed at using  level 1  file followed by level 2 file  having to be in the same folder is 
 there any means of being able to specify the structure as to where these files can be found?  
I am at the point of wondering if Commander is actually the best tool for me to use for the type of Command Line Interface that I want to put in place?

**Comment by evalcodenet** [comment] 2019-01-14 10:05
Following seems to work for me - though I'd also appreciate a proper solution. Grouping of commands and options would be nice too. And some option names conflict with the implementation of commander, e.g. 'name' or 'domain'.

```
commander
    .version('0.1.0')
    .description('CLI');

commander
    .command('deployment <command>')
    .description('Manage deployment')
    .option('')
    .option('create', 'Create deployment')
    .option('--cloud <provider>', 'Cloud provider', 'aws')
    .option('--region <region>', 'Region', 'eu-central-1')
    .option('--prefix <prefix>', 'Resource prefix', 'tld-domain')
    .option('')
    .option('update', 'Update deployment')
    .option('--prefix <prefix>', 'Resource prefix', 'tld-domain')
    .action((command, options) => {
        console.log(command, options);
    });
```

Can be invoked either way (though the help will produce `Usage: deployment [options] <command>`):
```
cli deployment create --prefix=my-domain
cli deployment --prefix=my-domain create
```

Generated Help - 1st Level
```
# cli --help
Usage: cli [options] [command]

CLI

Options:
  -V, --version                   output the version number
  -h, --help                      output usage information

Commands:
  init [options] [name]           Initialize project
  deployment [options] <command>  Manage deployment
  deploy [options]                Deploy project
```

Generated Help - 2nd Level
```
# cli deployment --help
Usage: deployment [options] <command>

Manage deployment

Options:
                      
  create              Create deployment
  --cloud <provider>  Cloud provider (default: "aws")
  --region <region>   Region (default: "eu-central-1")
  --prefix <prefix>   Resource prefix (default: "tld-domain")
                      
  update              Update deployment
  --prefix <prefix>   Resource prefix (default: "tld-domain")
```

**Comment by shadowspawn** [comment] 2019-10-02 07:59
There was an answer posted to the original post, which was options for a subcommand with an action handler.

There was an example posted for option getting passed down into sub-sub-command.

#563 is an open issue about program level options being available to executable subcommands.

Closing this issue as not covering something that will be actioned. Feel free to open a new issue if it comes up again, with new information and renewed interest.

Thank you  for your contributions.

**Closed by shadowspawn** 2019-10-02 07:59 UTC

**Comment by NaveenDA** [comment] 2019-12-12 17:56
Is there any way to show full help for subcommands commands like `npm -l`?

**Comment by shadowspawn** [comment] 2019-12-12 23:26
@NaveenDA No, see #1078. Nice example, thanks.

**Comment by shadowspawn** [comment] 2021-10-15 04:56
@kuncevic Commander does already list the subcommands in the program help. This is actually a bit like what `npm -l` does, which does not show the full subcommand help either.

Currently the info displayed for each subcommand is the command description, and you can put extra info in there. The same description is displayed in the subcommand help. (For interest, there is an issue about the opposite problem, that the detailed description was too much to list in the program help! #1291)

**Comment by nguyenthang338** [comment] 2021-10-15 05:12
i work for me used options in subcommand  don't need opts() fuctions. 
 program
  .command('upload')
  .description('upload a file')
  .option('-f, --file <file>', 'file name')
  .action(function(options) {
     myfunction(options.file) ; 
 
  });

 program.parse(process.argv);

**Comment by kuncevic** [comment] 2021-10-15 07:58
done https://github.com/tj/commander.js/issues/1624
