### ISSUE TITLE
Git-style sub-commands not working on Windows

### ISSUE THREAD

**Issue by MystK** [tj/commander.js#890] opened 2018-11-27 05:06 UTC
It looks like due to how Yarn v1.12.3/npm v6.4.1 handle bins compared to linux/mac, the sub-commands are not working.

![image](https://user-images.githubusercontent.com/7399140/49059644-b8b8d000-f1be-11e8-8dca-1acb3b6c52b5.png)

index should be the bin name, but it becomes the js file name
legion is the subcommand I am trying to run
It's trying to require the file in the root directory, but it should be searching in the folder that the bin was ran.

I traced it to line 569 inside of index.js of commander.

Is anyone else getting this or is it just something stupid I am doing? If it is an issue, I would be willing to make a PR. atm, I'm not sure how I can grab the bin file name though since I can't find it anywhere I've looked, including the process.argv.

![image](https://user-images.githubusercontent.com/7399140/49059750-3381eb00-f1bf-11e8-951f-71cdd8eef1f7.png)

**Comment by erolkskn** [comment] 2018-11-28 00:20
It's just how sub-command execution works. If you look at that line of code https://github.com/tj/commander.js/blob/d24008158d0870a6df2279dc93c7a36d3f41926d/index.js#L526 
it concatenates current executing filename and args[0] ( sub-command ). So what you are talking about is not a bug neither feature.

**Comment by MystK** [comment] 2018-11-28 00:48
@erolkskn the bug seems to be that the behavior is incorrect in windows but correct in linux.

Example:
if I run
```
git commit
```
and git actually points to /blah/index.js, on linux, it would try to call

```
git-commit.js
```

on windows, it calls

```
index-commit.js
```

On top of that, in windows, the path of where git-commit.js is seems to be incorrect.

**Comment by amily4555** [comment] 2019-02-26 04:05
the some question

**Comment by shadowspawn** [comment] 2019-04-03 08:21
The yarn issue may have been fixed in: https://github.com/tj/commander.js/releases/tag/v2.20.0

**Comment by Mousecop** [comment] 2019-04-17 14:44
Hello, I have updated to v2.20.0 and I am still having this problem. Is there a workaround or a resolution for this?
I am running a build command. On Linux it is expecting `test-build` but on Windows it is expecting `index-build`. Is there a way to satisfy both?
Thank you.

**Comment by shadowspawn** [comment] 2019-04-17 21:13
@Mousecop Have a look at #786 where people have done some digging into the name lookup. Basically, you want to reduce the variations: try naming your entry file the same as your command.

**Comment by shadowspawn** [comment] 2019-07-21 05:11
Pull Request being considered for v3 is #999, which will at least allow manual override

**Comment by shadowspawn** [comment] 2019-07-27 05:16
This issue will have at least a work-around when v3.0.0 is released. Available now as a prerelease. See #1001

**Comment by shadowspawn** [comment] 2019-08-10 00:52
.command now supports the executableFile option (thanks to @abetomo).
Shipped in v3: https://github.com/tj/commander.js/releases/tag/v3.0.0

**Comment by shadowspawn** [comment] 2020-02-05 06:26
I am closing this in favour of #714 which I think describes the same issue.
Duplicate of #714

**Closed by shadowspawn** 2020-02-05 06:26 UTC
