### ISSUE TITLE
Error when argument has same name as a flag

### ISSUE THREAD

**Issue by andy-hanson** [tj/commander.js#629] opened 2017-05-06 01:41 UTC
`a.js`:
```js
const c = require("commander");
c
    .option("--foo [value]")
    .parse(process.argv);
console.log({ foo: c.foo, args: c.args });
```
Usage:
```sh
$ node a.js arg --foo value
{ foo: 'value', args: [ 'arg' ] }
$ node a.js foo --foo value
{ foo: [], args: [] }
```

Expected `{ foo: 'value', args: [ 'foo' ] }`.

**Comment by shadowspawn** [comment] 2019-03-30 09:08
Closing as duplicate of #346

**Closed by shadowspawn** 2019-03-30 09:08 UTC
