### ISSUE TITLE
Command Description Broken with Action

### ISSUE THREAD

**Issue by pwdonald** [tj/commander.js#285] opened 2014-10-28 16:11 UTC
```
commander
    .version('0.0.1')
    .command('create <type> <name>','testdesc')
    .action(function(type, name) {
        // some code
    });
```
Results in:
```
  this.parent.on(this._name, listener);
              ^
TypeError: Cannot call method 'on' of undefined
```
Whereas it works when you remove the command description parameter.

**Comment by StoneCypher** [comment] 2015-01-16 18:57
This is still occurring, and should not be marked closed.

**Comment by StoneCypher** [comment] 2015-01-16 18:58
I am also facing this.

**Comment by StoneCypher** [comment] 2015-01-16 19:02
actually it may be that `.action` is broken entirely; even without `.usage(...)`, and an empty action function, the error still emits.

**Comment by StoneCypher** [comment] 2015-01-16 19:06
Aha.  If you first specify both `.command` and `.option`, then suddenly it works.

Note that the documentation does not mention either of these things.

**Comment by StoneCypher** [comment] 2015-01-16 23:27
Unfortunately, someone has closed bug #331 as a duplicate of this bug.

#331 is *not* a duplicate of this bug.

**Comment by zhiyelee** [comment] 2015-01-17 16:24
@StoneCypher  Indeed  it is intended. https://github.com/tj/commander.js#git-style-sub-commands

**Comment by StoneCypher** [comment] 2015-01-17 17:42
I don't see anything there saying that this is intended.

I wish you would stop closing bugs until you've talked to the people filing them.  You closed 331 as a duplicate over the filer's protest, and now you're closing this as intended with a doc reference where I can't tell why you think it's intended.

The open source norm is to talk to the people filing the bug, on the chance that you misunderstand.

Please re-open both bugs.

**Comment by StoneCypher** [comment] 2015-01-17 17:44
You appear not to have noticed that the thing you're saying intentionally doesn't work is ***what the documentation says should work***.

**Comment by zhiyelee** [comment] 2015-01-17 19:25
@StoneCypher Sorry,  I didn't made it clear.

The "bug" here is intended.   There should not be followed `.action`  when there is the second argument for the `.command`. In that case, the sub-command is treat as git-style command, and the app will try to execute  the `app-subcommand` script, such as `pm-install`, `pm-search` here: https://github.com/tj/commander.js/blob/master/examples/pm

Besides I also think #331  is not the same as this one, and I have reopened it.

**Closed by zhiyelee** 2015-01-17 19:25 UTC

**Comment by StoneCypher** [comment] 2015-01-18 10:00
Please consider having this abort with a meaningful error, rather than to fail in an obscure way, if it is indeed as designed.

**Comment by zhiyelee** [comment] 2015-01-18 11:43
@StoneCypher Yes, the error should be caught

**Comment by morseldesign** [comment] 2015-01-24 03:39
Agree, this is super confusing. Could you make this possible as opposed to having it error out?

```js
reporter.command('tacos <topping>', 'I should be supported.').action(function (topping) {
  if ( topping ) {
    console.log("Oh hey, you like " + topping + " on your tacos.");
  }
});
```

**Comment by addisonj** [comment] 2015-01-25 02:19
Agreed that this is strange behavior... 

This breaks the principle of least astonishment pretty hard. Seems like it would be much nicer to move that behind a third argument to `command`.

Perhaps:
```JavaScript
program('command', 'desc', {gitStyle: true}, function(){})
```

That said, with a bit of digging into the code, I was able to do what I want by doing:

```JavaScript
var subCommand = program.command('stuff')
subCommand.description('add this here')
subCommand.action(function() {..})
```
and also added a cleaner help action (which magically disappears when you aren't using git style subcommands)

```JavaScript
var commands = {}
commands[commandName] = subCommand
program.command('help <commandName>').action(function(name) {
  commands[name].outputHelp()
})
```

Hopefully that helps someone.
