### ISSUE TITLE
Feature Request: variadic arguments in .option()

### ISSUE THREAD

**Issue by majidsajadi** [tj/commander.js#1233] opened 2020-03-29 09:07 UTC
In the first parameter to .command()  the last argument may also be variadic....
So my question is why .option() doesnt have this feature?
Is there any reasone to not implement this?

**Comment by shadowspawn** [comment] 2020-03-29 09:47
It is complicated. 😄 
See #571

**Comment by shadowspawn** [comment] 2020-04-18 03:50
Closing as duplicate of #571

**Closed by shadowspawn** 2020-04-18 03:50 UTC
