### ISSUE TITLE
feature request: pre run and post run hooks

### ISSUE THREAD

**Issue by majidsajadi** [tj/commander.js#1197] opened 2020-02-15 12:00 UTC
How about option to add a preRun and a postRun function to each command to run before or after the main function?

**Comment by shadowspawn** [comment] 2020-02-15 21:06
This idea does come up occasionally. We need a good idea of what problem this is solving.

What problem would this help with? What is an example of what you would do in the preRun or postRun, and how would this be better than just calling it from the main function?

Related issues: #76 #936 #996

**Comment by majidsajadi** [comment] 2020-02-18 05:57
Opening database connection, creating directories or log file, etc.
We can call it from the main function but i guess it is better if we let the main function be about the command it self and not some repetitive functions.

Here is an example of a commander with support of prerun and postrun hooks

https://github.com/spf13/cobra#prerun-and-postrun-hooks

**Comment by shadowspawn** [comment] 2020-02-18 06:33
I looked at Cobra recently, has a lot of features. Good example thanks.

I see for pre/post Cobra has not two but four extra functions, with two of them specific to the command, and two of them "persistent" (I would have said inherited) and passed on to subcommands.

My first impression is pre/post hooks are going to be somewhat complex to use and of limited use.

I'm happy to leave this issue open though to see whether it generates further interest and insights.

**Comment by shadowspawn** [comment] 2020-06-01 03:21
One implementation complication with pre/post hooks would be if they should support async.

**Comment by ad-m** [comment] 2020-07-04 00:22
Hi,

We develop relatively extensive CLI (190 categories + 670 operations = 860 commands). Our CLI is contains multiple nested groups of commands. We are currently using structured-cli, which is abandoned and causes problems that require solutions in the engine. We tried to use commander.js. We quickly came across needs of plugins.

Our CLI is designed to manage cloud computing services. In practice, it is calling the platform API.

I developed my own mechanism around commander.js while trying to make a new CLI with it. So far I prepared plugins such as:
- api - provides API client initialization, including ensuring that the user has previously executed login commands, and if not - rejects the command until logging in, also supports the injection of additional login-related ones,
- formatOutput - adds parameters responsible for output formatting (similar to the "--output" and "--query" parameters available in CLI gcloud, aws and az), and also format the output accordingly,
- noWait - modifies the client-API so that it does not wait for the operation to complete after it is accepted by the API,
- validatorChoices - introduces parameter verifications in the range of acceptable values, e.g. acceptable output formats.
- formatError - format errors consuming standard error API format

The developed plugin mechanism turns out to be quite flexible in complementing the restrictions of commander.js in parameter parsing. Our plugins implementation wrap `action` in wrapper and promisify everyting:

```javascript
const createCommand = (options) => {
    options.handler = options.handler || (() => {
        throw new Error("Not implemented")
    })
    options.plugins = options.plugins || [];
    options.parameters = options.parameters || {};

    const cmd = new Command(options.name).storeOptionsAsProperties(false);
    if (options.description) {
        cmd.description(options.description);
    }

    for (const plugin of options.plugins.filter(x => x.beforeParameter)) {
        plugin.beforeParameter(options);
    };

    for (const plugin of options.plugins.filter(x => x.parameters)) {
        Object.assign(options.parameters, plugin.parameters)
    };

    for (const [name, config] of Object.entries(options.parameters)) {
        const flag = config.type == 'boolean' ? `--${name}` :`--${name} [${(config.placeholder || name).toUpperCase()}]`
        cmd._optionEx(
            { mandatory: config.required || false, },
            flag,
            config.description,
            config.validator,
            config.defaultValue
        )
    }

    const toolbox = {};

    const wrapper = () => {
        const ctx = { input: cmd.opts(), options, toolbox };
        let p = Promise.resolve(ctx);

        for (const plugin of options.plugins.filter(x => x.beforeHandler)) {
            p = p.then(() =>
                Promise.resolve(timingPromise(`${plugin.name}:beforeHandler`, plugin.beforeHandler(ctx)))
            );
        }

        p = p.then(() => timingPromise('handler', Promise.resolve(options.handler(ctx))))

        for (const plugin of options.plugins.filter(x => x.afterHandler)) {
            p = p.then(output => {
                return timingPromise(`${plugin.name}:afterHandler`, Promise.resolve(plugin.afterHandler(ctx, output)))
            });
        }

        for (const plugin of options.plugins.filter(x => x.error)) {
            p = p.catch(err =>
                timingPromise(`${plugin.name}:error`, Promise.resolve(plugin.error(ctx, err)))
            );
        }
        return p;
    };
    cmd.action(wrapper);

    return cmd;
}
```

From our point of view - promise in plugins is necessary to, e.g. download additional information from the API, e.g. regarding user login, but also in the case of verification of parameters provided by the user (currently we verify requests only after sending to the API).

As you can see, we will pack commander.js quite heavily to be able to use it for our needs. We currently have over 700 commands in CLI based on commander.js (most of them are generated on the basis of machine-readable documentation), but we're considering whether using commander.js is the way to go.

I hope these comments are helpful. I was considering using koa-compose for this, but I finally decided not to build our plugin interface around middleware.

**Comment by shadowspawn** [comment] 2020-07-04 00:43
Very interesting, thanks @ad-m

**Comment by ad-m** [comment] 2020-07-04 01:00
An additional note, the toolbox is a container that is forwarded and we anticipate that various plugins will add tools to it. Glugun have a lot of extensions like that: https://github.com/infinitered/gluegun/tree/master/src/core-extensions

**Comment by b-jsshapiro** [comment] 2020-08-13 14:17
@shadowspawn: The heart of the problem is that doing argument processing and execution as a single step has lost a phase distinction that matters for a whole bunch of CLIs. Offhand, I can't think of the last time I wrote a CLI application in UNIX that _didn't_ need to do some form of configuration or validation step based on argument input before running the core of the application. I'm actually very puzzled that essentially _every_ CLI handling package I have looked at seems to have omitted this phase distinction.

A common example is needing to process a config file whose filename can be overridden on the command line. You _can't_ process it until the command line is parsed (so you know the filename), but you _must_ process it before execution begins. Commander can handle this case by combining `requiredOption()` with a default, which I didn't see until I read the code. Nice job on that one, but that's a common enough case to be worth describing in the quick docs. It's not super obvious that one reason to use `requiredOption()` is to force the callback to happen when you have a default.

Another common example is anything that requires a sanity cross-check between multiple options. E.g. for mutual exclusion. The negatable boolean [no-]cheese/sauce example in your docs is a case where conflicting options should be diagnosed rather than accepted. That particular example can be managed adequately with callbacks, but that solution doesn't scale well. Consider what that callback would have to look like for a commander-based version of the UNIX _find_ or _cpio_ commands. The config file case can become an example of this if you want command line options to be able to override the defaults from the config file. 

For applications that need the phase distinction, I think a very simple refactoring would do the job, and it doesn't seem to require a breaking change. Commander already exposes `parseOptions()`. It's the very first thing called from `_parseCommand()`, which is the first _substantive_ thing called from `parse()`. So the option parsing part _per se_ isn't the problem. The problem is that after I call `parseOptions()` there's no way to go back and finish the job by running the command logic.

Here's my suggestion:

1. Move the `argv` compatibility handling for node/electron/whatever from `parse()` to `parseOptions()`, passing the same options object that you currently pass to `parse()` as a (new) optional trailing parameter to `parseOptions()`. That alone makes `parseOptions()` more useful without a breaking change.
2. Rename `_parseCommand()` to `_executeCommand()`, which is what it actually does. Drop the first line and have it accept the `parsed` return value from `parseOptions()` as a parameter.
3. Introduce a new public entry point `executeCommand(parsed)` which is (effectively) the current body of `executeCommand()` less the call to `parseOptions()`. This is a trivial wrapper around `executeCommand()`.

Early morning here after a short sleep, so that may not read as clearly as I think it does. Don't hesitate to reach out if clarification is helpful. I'd be glad to do the change and send you a pull request if you like.

**Comment by b-jsshapiro** [comment] 2020-08-13 14:42
Well darn. The `requiredOption()` callback _doesn't_ get called unless the option is actually passed on the command line. Bother.

And in regards to my previous, there's an easier approach. Add one line to the bottom of parseOptions() just before the return statement:

```
this.emit(`options-parsed', { operands, unknown });
```

Did I mention that it's early here? :-)

**Comment by shadowspawn** [comment] 2020-08-14 22:44
Separating the argument processing and execution would be hard, but might offer a simpler pattern than callbacks and events and hooks for at least some cases. Conceptually:

```js
const details = program.phase1_parse();
myPreRunProcessing(program, details);
program.phase2_run(stuff);
```

**Comment by shadowspawn** [comment] 2020-09-05 23:38
oclif has "hooks": https://oclif.io/docs/hooks#lifecycle-events
yargs has "middleware:: http://yargs.js.org/docs/#api-reference-middlewarecallbacks-applybeforevalidation

**Comment by shadowspawn** [comment] 2021-04-28 06:13
@chriscalo asked about a way to set environment variables from options before the action handler is called: https://github.com/tj/commander.js/issues/1457#issuecomment-827961725

**Comment by shadowspawn** [comment] 2021-05-07 03:52
Trying out some names:

```
program.hook("beforeAction", () => console.log('beforeAction'));
```

**Comment by shadowspawn** [comment] 2021-05-23 03:31
Command v8 has life cycle hooks for `preAction` and `postAction`. Prerelease available now.

**Comment by shadowspawn** [comment] 2021-06-25 08:40
Released in Commander v8.

**Closed by shadowspawn** 2021-06-25 08:40 UTC
Labels: enhancement
