### ISSUE TITLE
Is there a guide for typescript based commands?

### ISSUE THREAD

**Issue by andrewkfiedler** [tj/commander.js#1479] opened 2021-03-01 18:57 UTC
I'm not sure this is an issue, but googling and searching existing issues took me to a dead end.

I'm using typescript, and some of the tricks from https://github.com/tj/commander.js/issues/955#issuecomment-490016192

Basically, I have a script where I want to pass in things like port and host.

My package.json has a script like:
```
"pa11y": "TS_NODE_PROJECT=./dev/tsconfig.json node -r ts-node/register ./check-accessibility.tsx",
```
So from the command line I want to be able to do this:
```
npm run pa11y -- -p=9000
```
Unfortunately I see I an issue when I do that, it says unrecognized option '-=9000'.

Doing the below works, but the option isn't set to 9000:
```
npm run pa11y -- -p 9000
```

Any tips?

**Comment by shadowspawn** [comment] 2021-03-01 19:51
> Any tips?

Lots! (If these don't help you get it working, then a reproducible example will help pin down the problem.)

1) That calling syntax was from someone using a stand-alone executable to implement the subcommand, and with a custom location to the tsconfig file. 

If you are using action handlers for the subcommands and a standard location for the config file, you can simplify the run-script to:

```
"pa11y": "ts-node ./check-accessibility.tsx",
```

2) Running things through an npm run-script means you have to protect your command options from being read by npm. That is why there is the `--`. (You may know this, just clarifying the layers you are going through!)

3) `-p=9000` is not a valid format for specifying the option. You can use:

- `-p 9000`
- `-p9000`
- `--port 9000`
- `--port=9000`

4) But all of that does not explain why your last calling attempt did not work! Two suggestions:

a) write out "process.args" at the start of your program. Your issue is more likely to be with the chain of programs having a look at the command-line arguments before they reach your program, than with TypeScript or your program.

b) Try running your script more directly to check it is actually working as intended. If you have ts-node installed as a dependency then:

```
npx ts-node check-accessibility.tsx -p 9000
```

or if ts-node is installed globally then just:

```
ts-node check-accessibility.tsx -p 9000
```

**Comment by shadowspawn** [comment] 2021-03-01 20:00
Oh, that was all good advice but... Have you specified that your option takes a value?

```
.option('-p,--port <number>', 'specify the port number')
```

(I think perhaps the "unrecognized option '-=9000'" came from Commander trying to expand `-p=9000` into multiple options, like `-ab` expanding into `-a -b`.)

**Comment by andrewkfiedler** [comment] 2021-03-01 20:01
Thanks, for all the details, I'll look at this thoroughly and if I figure out where I went wrong I'll post here.  I'll also post if I don't, but with a reproduction.

**Comment by andrewkfiedler** [comment] 2021-03-01 20:59
Okay, so I tried both `npx` to run it without going through npm, and through npm.  With both I see this:
```
Andrews-MacBook-Pro:jhipster-uswds-react-output andrewfiedler$ npx ts-node -P ./dev/tsconfig.json check-accessibility.tsx -p 9000
[ '/repos/octo/fedhipster-work/jhipster-uswds-react-output/node_modules/.bin/ts-node',
  '/repos/octo/fedhipster-work/jhipster-uswds-react-output/check-accessibility.tsx',
  '-p',
  '9000' ]
{ secure: false, silent: false, port: '8080' }
```

```
import { Command } from 'commander';
const program = new Command();
console.log(process.argv);
program
  .option('-p,--port', 'port', '8080')
  .option('-h, --host', 'host', 'localhost')
  .option('-s, --secure', 'https instead of http', false)
  .option('-silent, --silent', `turn off showing non compliances (logs are still saved)`, false);
program.parse(process.argv);

```

Here's the entire file in case there's something funky I'm doing:
```
import pa11y from 'pa11y';
import glob from 'glob';
import fs from 'fs';
// import path from 'path'; // only needed for shorter name
import prettier from 'prettier';
const rimraf = require('rimraf');
const DIR_NAME = 'accessibility'; // do we want to name it something else?  dist?  doesn't matter much to me.  Add to gitignore

// defines some things that might be useful in case folks want to run this in different environments (dev, prod)
import { Command } from 'commander';
const program = new Command();
console.log(process.argv);
program
  .option('-p,--port', 'port', '8080')
  .option('-h, --host', 'host', 'localhost')
  .option('-s, --secure', 'https instead of http', false)
  .option('-silent, --silent', `turn off showing non compliances (logs are still saved)`, false);
program.parse(process.argv);
const { p: PORT = '8080', h: HOST = 'localhost', s: SECURE = false, silent: SILENT } = program.opts();
const PROTOCOL = SECURE ? 'https' : 'http';
console.log(program.opts());
console.log(process.argv);

const getFileNameFromFile = (file: string) => {
  return file.split('/').join('-').split('.')[0]; // unique filename formed by turning / into - and removing the ext
  // path.basename(file, path.extname(file)).split('.pa11y')[0]; // alternative, much shorter filename, but not
};

// remove the dir, recreate (pa11y cannot gen dirs), read each config and run the actions specified (take screenshot and write out results)
rimraf(`./${DIR_NAME}`, () => {
  fs.mkdirSync(`./${DIR_NAME}`);
  glob('**/*.pa11y.json', {}, (er, files) => {
    files.forEach(file => {
      const fileJSON = JSON.parse(fs.readFileSync(file, 'utf8'));
      const fileName = getFileNameFromFile(file);
      fileJSON.screenCapture = `${__dirname}/${DIR_NAME}/${fileName}.png`;
      pa11y(`${PROTOCOL}://${HOST}:${PORT}/${fileJSON.url}`, fileJSON).then(results => {
        const reportName = `./${DIR_NAME}/${fileName}.json`;
        fs.writeFileSync(
          reportName,
          prettier.format(JSON.stringify(results), {
            parser: 'json',
          })
        );
        if (!SILENT) {
          console.log(results);
        }
      });
    });
  });
});

```

I feel like I'm probably making some obvious mistake 🤔

**Comment by shadowspawn** [comment] 2021-03-01 21:05
Quick answer. You need to specify that your options for host and port require a value:

```
  .option('-p,--port <number>', 'port', '8080')
  .option('-h, --host <name>', 'host', 'localhost')
```

**Comment by andrewkfiedler** [comment] 2021-03-01 21:06
🤦 Thank you so much.  I need to read more and code less sometimes 🎉

**Comment by shadowspawn** [comment] 2021-03-01 21:13
I thought it was going to be trickier too with the question title about TypeScript, and example using a run-script and custom env, and...

But you successfully navigated all the other potential issues!

(And the error message from Commander is not great.)

**Comment by andrewkfiedler** [comment] 2021-03-01 21:16
That was might thought too!  I thought it had to be something not passing things through correctly.  Glad it turned out much simpler.

Yeah, I was going to spend some time seeing if it was possible to contribute back some warning message or something for folks, but not sure how the parsing is done and whether that'd be possible.

**Comment by andrewkfiedler** [comment] 2021-03-01 21:57
![Screen Shot 2021-03-01 at 2 56 01 PM](https://user-images.githubusercontent.com/11984853/109564431-4a020580-7a9e-11eb-94b8-d25496ffcc93.png)

Maybe it would make sense to check here?  I debugged to this point and noticed that there is parsed.operands of 9000, but it doesn't show up as parsed.unknown.

**Comment by shadowspawn** [comment] 2021-03-02 08:12
This is where the combined short options or short option and value get handled:
https://github.com/tj/commander.js/blob/4aaaa9de3fd09401afe3894483193ba0e2e512d7/index.js#L1636

The error currently gets detected  later after the recognised option has been eaten, so lost the context for a clear error.

**Comment by shadowspawn** [comment] 2021-04-02 09:16
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2021-04-02 09:16 UTC
