### ISSUE TITLE
Match help information with `.parse({ from })`

### ISSUE THREAD

**Issue by hypeJunction** [tj/commander.js#2276] opened 2024-11-01 10:23 UTC
Displayed help information does not align with what the user input actually is, in case `from` property is set during parsing. Help still shows the main command from `node` perspective.

**Comment by shadowspawn** [comment] 2024-11-01 20:55
I am not sure what the problem is. Can you give an example of what you are trying to do and what you see?

**Comment by hypeJunction** [comment] 2024-11-01 21:35
I will post an actual example when I am back at my computer. The problem is that help prefixes the command with the program name, even though it parses just the command. Parsing user input actually fails if you add the name of the program before it.

**Comment by hypeJunction** [comment] 2024-11-01 21:50
Here is the Screencast I made earlier. As you see what help says is not what you have to type to execute a command.
[382253310-ca079a5c-2f15-4d66-ae47-b3e7bb0fd270.webm](https://github.com/user-attachments/assets/16a9de3d-f085-45d9-a1c2-650cb9c8ebbf)

**Comment by shadowspawn** [comment] 2024-11-01 22:29
Ah, I see. The help does assume it should show the root command (program) in the usage.

A quick hack would be to set the program name to a space. There will be some extra spaces in the displayed usage, but really easy!

```js
program.name(' ');
```

A full solution is to change the method building the usage. (You could leave out the `ancestorCmdNames` related code if you don't have nested subcommands.)

```js
// Do now include the "program name" since it does
// not make sense in our usage.
program.configureHelp({
  commandUsage: (cmd) => {
    if (!cmd.parent) return cmd.usage();

    let cmdName = cmd.name();
    if (cmd._aliases[0]) {
      cmdName = cmdName + '|' + cmd._aliases[0];
    }
    let ancestorCmdNames = '';
    for (
      let ancestorCmd = cmd.parent;
      ancestorCmd && ancestorCmd.parent;
      ancestorCmd = ancestorCmd.parent
    ) {
      ancestorCmdNames = ancestorCmd.name() + ' ' + ancestorCmdNames;
    }
    return ancestorCmdNames + cmdName + ' ' + cmd.usage();

  }}
);

const fooCommand = program.command('foo');
const barCommand = fooCommand.command('bar');
```

```console
$ node repl.mjs --help | head -n 1
Usage: [options] [command]
$ node repl.mjs foo --help | head -n 1
Usage: foo [options] [command]
$ node repl.mjs foo bar --help | head -n 1
Usage: foo bar [options]
```

**Comment by shadowspawn** [comment] 2024-12-27 23:51
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed** 2024-12-27 23:51 UTC
