### ISSUE TITLE
(1) does not exist, try --help

### ISSUE THREAD

**Issue by zoecarver** [tj/commander.js#786] opened 2018-04-08 18:23 UTC
After calling 
``` JavaScript
program.parse(process.argv);
```
I get 
```
index-server(1) does not exist, try --help
```
### Commands Run
```
$ node ../../lib/cmd/index.js server
```
### Relevant Code
```JavaScript
// index.js
const { root } = require('./root');
root.parse(process.argv);

//root.js
import * as root from "commander";
root
  .version(version, "-v, --version")
  .description("description")
  .option("-s, --select <id>", "select")
  .option("-e, --env <env>", "Environment to use for commands.")

export { root }

**Comment by JohnRGee** [comment] 2018-04-14 23:27
I was not able to reproduce with your code fragment, but it looks like you have (accidentally) invoked the [Git-style sub-commands](https://github.com/tj/commander.js#git-style-sub-commands) processing which searches for separate executables. 

Do you have code like `root.command("server", description)` in your failing program?

**Comment by fabioricali** [comment] 2018-08-09 08:53
I have same issue on Mac! Windows works.

**Comment by knyy** [comment] 2018-08-24 13:03
Is there a workaround/fix for this issue? It's affecting my automated build on linux as well, works fine on windows.

**Comment by fabioricali** [comment] 2018-08-24 14:56
It's terrible but works fine 🥇 

I'have created a simple file he is looking for
https://github.com/dozjs/doz-cli/blob/master/src/doz-component.js

**Comment by knyy** [comment] 2018-08-27 06:26
@fabioricali thanks for sharing, can you help me to understand the necessary changes to patch my application?

**Comment by knyy** [comment] 2018-08-27 10:37
Here is the workaround I am using for my project:
For windows the **value** ./my-script-<command-name> is used to try and find the executable file.
For unix the **key** "my-script-<command-name>" is used to try and find the executable file.

If the key and value in package json bin is the same it works fine on both unix and windows. We wont get the not found error (which occurs if package.json 's package.bin is "my-script" : "./index.js").

package.json:
```js
... 
{
 "bin" : { "my-script": "./my-script.js" }
}
...
```
my-script.js
```
  var program = require('commander');
  program
    .command('start', 'Start application dev server.') // sub-command name
    .command('build', 'Build application artifacts.')
    .command('test', 'Run tests in application.')
    .command('generate', 'Generate application w/ scafolding.')
    .parse(process.argv);
```
Folder structure:
```
./my-scripts.js
./my-scripts-build.js
./my-scripts-start.js
./my-scripts-generate.js
./my-scripts-test.js
```

**Comment by jameelmoses** [comment] 2018-10-25 17:10
any update on this? ive tried @fabioricali and @knyy's workarounds with no success.

i cannot reproduce the issue locally using `yarn link` or `npm link` but after publishing to npm and installing with yarn, the issue appears.

also, if i remove the globally installed yarn package and install with npm instead of yarn it works

**Comment by dandananddada** [comment] 2018-11-02 13:13
So how to fix this issues?

**Comment by JohnRGee** [comment] 2018-11-03 09:40
Looking at the code and experimenting, `commander` effectively uses `argv[1]` to construct the filename for the subcommand. (Actually the second argument to `.parse()` ) This can give different results depending on the launch method if your command name, and package folder name, and source filename differ.

Suppose you have a subcommand and have not created its source file yet:

```
program.command('generate', 'Generate application w/ scafolding.')
```

With the package in a directory called `fab-dir` which installs a command `fab` which runs a file called `index.js`, I see these results on macOS:

```
$ npm link
$ fab generate
error: fab-generate(1) does not exist, try --help
# as argv[1] was the installed command name

$ node index.js generate
error: index-generate(1) does not exist, try --help
# as argv[1] was the source filename

$ node . generate
error: fab-dir-generate(1) does not exist, try --help
# as argv[1] was the folder of the package

```

**Comment by david-mohr** [comment] 2019-04-02 23:19
I'm on Linux and found this issue while searching for subcommand "does not exist" errors.  Simliar to @jameelmoses I found that `yarn global` was causing the issue.  Yarn has changed from symlinking `/usr/local/bin/exe` directly to the `node_modules` folder to using an intermediate `.bin` folder which then continues to link onto the `node_modules` folder.

In short, `commander` is stuck looking for `.bin/exe-sub` which doesn't exist, but `node_modules/exe/exe-sub` does.  I have found a few possible workarounds:
- Put this `.bin` folder first in `$PATH` and therefore the symlink will point to `node_modules` and everything works as expected
- Add additional entries to `package.json` for the other `bin` options
- Use `npm -g` instead of `yarn global`

**Comment by shadowspawn** [comment] 2019-04-02 23:25
Thanks for the work-arounds @david-mohr

There is a change being prepared for release in Commander v2.20.0 which should help with the Yarn issue in particular: #935

**Comment by acds** [comment] 2019-06-25 23:53
@shadowspawn did it make the 2.20.0 release - I fear not

**Comment by shadowspawn** [comment] 2019-06-26 00:40
@acds 
The change from #935 is in v2.20.0. 
https://github.com/tj/commander.js/compare/v2.19.0...v2.20.0

**Comment by shadowspawn** [comment] 2019-07-27 04:48
There will be a work-around for this issue when v3.0.0 is released, with an `executableFile` option to provide custom name. Available now as a prerelease. See #1001

**Comment by shadowspawn** [comment] 2019-08-09 09:19
Reworked the README and JSDoc and TypeScript to hopefully make the two modes of operation clearer. Have not changed the runtime, but will close this issue and see how the changes help.

Shipped in v3: https://github.com/tj/commander.js/releases/tag/v3.0.0

**Closed as completed by shadowspawn** 2019-08-09 09:19 UTC
