### ISSUE TITLE
Options are always empty

### ISSUE THREAD

**Issue by PsotnyPerun** [tj/commander.js#1761] opened 2022-06-25 20:47 UTC
Hi, 
I've been trying both my own code and code from the samples, and whatever I do options are always empty. 
But let's stick with the examples - I've been trying using this one: https://github.com/tj/commander.js/blob/master/examples/pizza. I've been trying to pass a custom string to --cheese option but whatever I do, options in program.opts() are always empty. They only get populated if there is a default value specified in option() function. 

On a Win machine, I've been running the script with npm run start --cheese=my_value or npm run start -c my_value and nothing would work. Even if the options are bools, adding --peppers still wouldn't work. 

I've been trying both the latest version (9.3.0) and some old ones from a year ago. 

Am I missing something obvious here?
Thanks!

**Comment by shadowspawn** [comment] 2022-06-25 21:11
Lots of people encounter this problem! The issue is invoking your script through `npm`. It is silently eating the options and they do not reach your script. I'll run through some general tips and the way to solve it.

A useful debugging step is to check what is reaching your script: `console.log(process.argv)`

Try running your script directly with node to check it is working as expected:
```
node script.js --cheese=my_value
```

For calling through `npm run`, you can use `--` to tell npm to stop looking for options. The `--` is a commonly supported way to tell something looking for options to stop looking! (Commander supports this too.) You can put the `--` anywhere after the options intended for npm and before the options intended for your script. 

```
npm run -- start --cheese=my_value
npm run start -- --cheese=my_value
```

The npm documentation page shows the `--` in the synopsis:

```
npm run-script <command> [-- <args>]
```

https://docs.npmjs.com/cli/v8/commands/npm-run-script

**Comment by PsotnyPerun** [comment] 2022-06-26 11:09
Oh, I see what you mean - it does make sense now. 
Adding -- when calling `npm run` did solve the issue.

Thank you for your help and for getting back to me so quick.

**Comment by shadowspawn** [comment] 2022-07-22 08:18
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2022-07-22 08:18 UTC

**Comment by kunanyi** [comment] 2024-02-26 12:20
Oh thank God I found this lol

Maybe consider adding the npm/-- trick to the docs?  I almost gave up :)
