### ISSUE TITLE
It causes unexpected result if arguments are the same as option name

### ISSUE THREAD

**Issue by zlargon** [tj/commander.js#483] opened 2016-01-02 10:14 UTC
This issue is quite similar to #471.

``` javascript
var program = require('commander');

program
  .option('-f, --foo', 'add some foo')
  .parse(['node', './test.js', 'foo']);

console.log(program.args);  // program.args = []
console.log(program.foo);   // program.foo = []

// Expected Result:
// program.args = ['foo']
// program.foo = undefined
```

**Comment by SomeKittens** [comment] 2016-01-25 17:57
I'm not quite ready to say this is a dupe of #471, as 'version' is somewhat internal, and you've added `foo`.

**Comment by ericuldall** [comment] 2016-03-26 07:03
Pull request #515 would fix this issue.

**Comment by ericuldall** [comment] 2016-03-26 07:16
The bug is with `Command.prototype.parseOptions`:

When looping over the options passed it accepts any values. It should perhaps only accept values that `.match(/^-.*/)`

**Comment by ericuldall** [comment] 2016-03-26 07:23
I've added a fix proposal to pull request #517

**Comment by ericuldall** [comment] 2016-03-26 07:26
The "fix" seems to be breaking other features, per failed unit tests. I'm not sure what or why at this point. Once the two play nice it should be useable.

**Comment by ericuldall** [comment] 2016-03-26 08:40
It looks like many of the unit tests don't work when this functionality is fixed. Many of them pass options that are not defined as `.option`. So now the tests are throwing the error:

```
error: unknown option `--setup_mode'
```

To me, this seems like the correct behavior, though these will not pass a travis-ci build.

**Comment by shadowspawn** [comment] 2019-03-30 09:07
Closing as duplicate of #346

**Closed by shadowspawn** 2019-03-30 09:07 UTC
