### ISSUE TITLE
My options seem to be undefined

### ISSUE THREAD

**Issue by Gacnt** [tj/commander.js#541] opened 2016-05-25 03:13 UTC
Trying to use commander like so:

```
const program = require('commander'),
      Excel     = require('exceljs'),
      colors    = require('colors/safe'),
      inquirer  = require('inquirer'),
      async    = require('async');

var fileName;

program
  .usage('[options] <file>')
  .option('-n', '--po-number <n>', 'The PO number to start at')
  .action(function(options, file) {
    fileName = file;
  })
  .parse(process.argv);

console.log(program.poNumber); // undefined


./index.js -n 636 ~/Docs/POList.xlsx
```

But `program.poNumber` is undefined

I've looked at numerous tutorials / docs on github but can't seem to figure out why it's undefined.

Node version 5.4.1

**Comment by cstolli** [comment] 2016-08-17 20:43
👍 

I'm having the same problem, my options suddenly just get swallowed and aren't available on the `program` object anymore

**Comment by jasonbarone** [comment] 2016-08-28 03:22
Same problem. I'm having an issue with options like `-d, --domain` and `-f, --filename`. Not sure why...

**Comment by casterstone** [comment] 2016-11-08 06:55
@Gacnt your example has an error.  The option flags are not separate arguments, it's one argument with the comma in the string.  It should be:

```
  .option('-n, --po-number <n>', 'The PO number to start at')
```

@jasonbarone using `-d, --domain <d>` works for me, but the short form with argument `-d <d>` fails

**Comment by tjdavenport** [comment] 2017-03-28 22:31
Having same issue. My options object is undefined. I've tried several combinations.

``` javascript
program.command('dev')
  .description('Start the VT frontend suite')
  .option('-p, --port <port>', 'Port number the express server will listen on.')
  .option('-s, --socketPort <socket>', 'Port number the socket server will listen on.')
  .action((env, options) => {
    console.log(options); //undefined
  });
```

**Comment by bitstrider** [comment] 2017-03-29 02:13
@tjdavenport you never specified an `env` command in your example, so `options` is the first argument.

```javascript
...  
  .action((options) => {
    console.log(options.port); // 1337
  });
```

**Comment by shmup** [comment] 2018-04-16 18:03
My options has been `undefined` too.

```
  program.command('foo')
    .option('-a, --all', 'show all used and unused parameters')
    .action((cmd, options) => {
    })
```

For now we've been just checking for the option in cmd, since it will be in there, among everything else. Options is undefined.

**Comment by Kaltemrix** [comment] 2019-02-07 03:22
The way i got this working on my end was adding `--` after the `npm start`
E.g. `npm start -- <option>`

**Comment by mtrabelsi** [comment] 2019-02-12 17:25
this is pretty annoying, if we are not able to pass strings to option, then this library is completely worthless

**Comment by vanesyan** [comment] 2019-02-13 13:52
> @bitstrider can you explain what you mean by "you never specified an env command/argument in your example"

`dev` command in the example above is defined without any argument i.e.:
```
program.command('dev')
```
So it won't receive any `env` argument and the first is an options as intended. If the `dev` command
were defined like:
```
program.command('dev <env>')
```
then, yes, it will receive options as the second argument and the first one will be equal to the value provided per `dev`.

**Comment by vanesyan** [comment] 2019-02-13 13:52
See #914 for the solution

**Closed by vanesyan** 2019-02-13 13:52 UTC
