### ISSUE TITLE
Accept negative number values

### ISSUE THREAD

**Issue by dresende** [tj/commander.js#61] opened 2012-06-01 11:43 UTC
I noticed that negative values are seen as possible options because of the minus sign. What I'm trying to do:

`node something.js --value -10`

Please note that `--value` is defined as `--value <n>` so it should accept it, I think.

**Comment by BrandonE** [comment] 2015-02-03 18:52
I have encountered an edge case for the provided solution.

```
node something.js --value=-10
```

It is valid for an equal sign to be provided. Because the minus is not in the first position of the argument, this fix won't work. Further:

```
node something.js --value='-Minus'
```

String values that start with a leading minus fail as well.

**Comment by lucasfcosta** [comment] 2015-10-04 16:24
Is this going to be fixed?

**Comment by Christilut** [comment] 2016-05-29 19:04
Also encountered this issue, working around it by doing: `-t \'-123\'` which results in the value being `'-123'` so after removing the first and last quote, its all good.

**Comment by shotamatsuda** [comment] 2017-02-27 09:15
Escaping a leading space also seems to work around this issue without less side effects: `-t \ -123`

**Comment by vanesyan** [comment] 2017-06-19 18:50
You can just simply pass the value in quotes and should works as expected. Imho, it's bad idea to assume digits as value, rather than flags, some of linux programs use digits as flags.

**Comment by vanesyan** [comment] 2017-06-19 18:51
Closed, answered. Feel free to reopen.

**Comment by kachkaev** [comment] 2017-06-20 14:39
`--value \ -42` works indeed, but neither of `--value=-42`, `--value="-42"` or ``--value='-42'` do. The options that do not work at the moment look more intuitive so should probably need to enabled at some point. Maybe PR https://github.com/tj/commander.js/pull/583 will help?

**Comment by vanesyan** [comment] 2017-06-20 15:20
you can run `--value '-42'` and it should perfectly work.

**Comment by kachkaev** [comment] 2017-06-20 15:28
Looks like it does not both for `--value '-42'` and `--value "-42"`

`commander@2.9.0`

**Comment by vanesyan** [comment] 2017-06-20 15:29
Okay, I'll investigate

**Comment by Simplonium** [comment] 2018-11-19 14:56
Is this 2 year old issue going to be fixed? Many command-line interfaces use negative numbers as arguments.

**Comment by the-townsend** [comment] 2019-01-07 16:42
Hi 
We're really pleased with commander.js and are using in our project - Thank you! It would be great if we could hand it negative numbers if someone has the capacity to make that change; our project has a messy work around at the moment. Thanks again.

**Comment by ecruzado** [comment] 2019-04-25 16:24
any updates on this issue? there is a timeline to fix it?

**Comment by shadowspawn** [comment] 2019-04-25 20:49
The current behaviour is that an option with a required value takes the following argument, whether or not it starts with a dash, so works with negative numbers.

Hopefully this covers your use cases @Simplonium @the-townsend @ecruzado ?

```
const program = require("commander");

program
.option("-n, --number <value>");

program.parse(process.argv);
console.log(program.number);
```

```
$ node index.js 
undefined
$ node index.js -n 1
1
$ node index.js -n -2
-2
$ node index.js --number=3
3
$ node index.js --number=-4
-4
```

Limitation: negative numbers are not recognised for options with a value which is only optional (e.g. `-n, --number [value]`), but I suspect this form gets used accidentally more often than by design. The complication with making that case work with negative numbers is that it would conflict with digits as flags as @vanesyan noted earlier.

**Comment by the-townsend** [comment] 2019-04-27 10:20
Thanks for this John, I’ll take a look.


________________________________

**Comment by shadowspawn** [comment] 2019-06-22 06:41
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2019-06-22 06:41 UTC
Labels: bug
