### ISSUE TITLE
Require an option

### ISSUE THREAD

**Issue by dzek69** [tj/commander.js#909] opened 2019-01-22 12:01 UTC
Can I define option as required?
I want to create ffmpeg-like cli experience and want person to always include `-i` option with a value. I can manually detect that `-i` wasn't given, but I want commander to do it for me.
Is it possible?

If yes - then I think README and API Docs need some examples, if not - I'd like make this a feature request.

Example
```javascript
program .option("-i <path>", "source file")
```

This fails on:
`app -i`

but continues on:
`app`

**Comment by shadowspawn** [comment] 2019-04-23 21:45
Answer provided, and enhancement covered by existing issue. Closing in favour of #230 

Duplicate of #230

**Closed by shadowspawn** 2019-04-23 21:45 UTC
