### ISSUE TITLE
Git-style subcommand alias not working 

### ISSUE THREAD

**Issue by lbai001** [tj/commander.js#628] opened 2017-05-03 18:51 UTC
Seems like the alias for git-style subcommand is not working for us, we've tried
```
program.command('generate [thing] [name]', 'generate a new controller').alias('g');
```
and here's the outcome: 
```
Commands:

    generate [thing] [name]  generate a new controller
    help [cmd]               display help for [cmd]
```
it looks like its not taking the alias attached at the end of the main command, is there anything missing from this code snippet? 

It looks like this was supposedly merged 10months ago in 2.9.0 but we are still experiencing errors.

**Comment by mbilbille** [comment] 2017-05-04 20:31
Yep, it has been merged but not released.
Here is a bypass https://github.com/tj/commander.js/issues/419#issuecomment-244262193

**Comment by lbai001** [comment] 2017-05-06 00:54
@mbilbille thanks a bunch :D

**Comment by shadowspawn** [comment] 2019-05-20 11:00
I was not able to reproduce this. (Hopefully fixed!)

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Closed by shadowspawn** 2019-05-20 11:00 UTC
