### ISSUE TITLE
-h help flag collides with user defined -h

### ISSUE THREAD

**Issue by nickgarvey** [tj/commander.js#645] opened 2017-06-22 06:45 UTC
Configuration:
User defines their own flag that uses -h

Expected behavior:
Running tool --help doesn't include -h as short hand for --help

Actual behavior:
-h is included for both --help and the custom flag

e.g.
```
ngarvey@challenger:~/projects/screeps-docker$ docker run tester cli --help

  Usage: cli [options]

  Connect to the CLI interface of the main process.

  Options:

    -h, --help         output usage information
    -p, --port <port>  Default is 21026
    -h, --host <host>  Default is localhost
```

**Comment by vanesyan** [comment] 2017-06-24 19:38
Duplicate of #400

**Comment by vanesyan** [comment] 2017-06-24 19:39
My bad, misunderstood

**Comment by shadowspawn** [comment] 2019-04-26 22:51
If someone wants to have a go at this, there is some code in #658 to reference which is doing the right things, but I had some style concerns. (Optionally could also cope with user defined `--help` although since much less likely than `-h`, it is fine to leave that out of this fix.)

**Comment by shadowspawn** [comment] 2020-04-25 04:00
The masked help options are no longer displayed from Commander v5.1.

https://github.com/tj/commander.js/releases/tag/v5.1.0

Thank you  for your contributions.

**Closed by shadowspawn** 2020-04-25 04:00 UTC
Labels: enhancement, pending release
