### ISSUE TITLE
Sub Sub command issues

### ISSUE THREAD

**Issue by celogeek** [tj/commander.js#527] opened 2016-04-25 20:09 UTC
Hi,

I want to create a git style subcommand, with subcommand.

I've got :
- git-redmine-tasks-info.js
- git-redmine-tasks.js
- git-redmine.js

so:
- git redmine has a command 'tasks'
- git redmine tasks has a command info
- git redmine tasks info 1234

git redmine tasks info require the directory 'git-redmine-tasks' exists but the 'git-redmine-tasks-info.js' don't need to be in it.

I've got this error :

```
$ git redmine tasks info
fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/home/dev/.npm/lib/node_modules/git-redmine-suite/git-redmine-tasks'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at exports.readlinkSync (/usr/home/dev/workspace/node/GRS/node_modules/graceful-readlink/index.js:5:7)
    at Command.executeSubCommand (/usr/home/dev/workspace/node/GRS/node_modules/commander/index.js:502:14)
    at Command.parse (/usr/home/dev/workspace/node/GRS/node_modules/commander/index.js:463:17)
    at Object.<anonymous> (/usr/home/dev/workspace/node/GRS/git-redmine-tasks.js:7:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

Here the different part of the code :

git-redmine.js

```
#!/usr/bin/env node
var p = require('commander');

p
.version(require('./package.json').version)
.command('tasks', 'manage tasks')
.parse(process.argv);

if (!p.args.length) {
  p.outputHelp()
}
```

git-redmine-tasks.js

```
#!/usr/bin/env node
var p = require('commander');

p
.version(require('./package.json').version)
.command('info', 'info on package')
.parse(process.argv);

if (!p.args.length) {
  p.outputHelp()
}
```

git-redmine-tasks-info.js

```
#!/usr/bin/env node

var p = require('commander');

p
.version(require('./package.json').version)
.parse(process.argv);

if (!p.args.length) {
  p.outputHelp()
}
```

**Comment by tcoupin** [comment] 2016-05-30 13:28
I found a workaround : remove all ".js" suffix

**Comment by Randgalt** [comment] 2016-07-26 22:31
I'm getting this as well.

**Comment by hedgerh** [comment] 2016-09-02 01:44
Removing the `.js` suffix fixed it for me in `2.9.0`, but for anyone else who runs into this problem, it appears that a fix has been merged into `master`, but not published to npm yet.

**Comment by gentunian** [comment] 2016-09-23 23:23
And sub subcommand does not force to show you help when you don't provide required options. It only says nothing and you should check options by yourself.

**Comment by DaniJG** [comment] 2017-06-06 17:35
It might not be entirely clear from the description, but there is another workaround apart from removing the `.js` suffix.  You just need to make sure you have an empty folder like `/bin/git-redmine-tasks/`, even if the .js files do not need to be there.

If you are building a new cli tool named `foo` you basically end up with something like:

- `/bin/foo.js`
- `/bin/foo-add.js`
- `/bin/foo-add-component.js`
- `/bin/foo-add/`  --empty folder, or maybe containing a README.md explaing why its there

And then you will have `foo`, `foo add` and `foo add component` all available in your cli.

**Comment by shadowspawn** [comment] 2019-08-03 23:04
I am not able to reproduce this issue, and expect it has been fixed, as there have been a few improvements to the separate executable lookup (git-style subcommand).
 
Thank you  for your contributions.

**Closed by shadowspawn** 2019-08-03 23:04 UTC
