### ISSUE TITLE
Pass unknown also as a second argument to the command:* event

### ISSUE THREAD

**Issue by negiDharmendra** [tj/commander.js#921] opened 2019-02-25 11:02 UTC
We are trying to use [this](https://github.com/tj/commander.js) awesome library to handle command line arguments and flags in [Taiko](https://github.com/getgauge/taiko/blob/master/README.md).
```
Example:

taiko [option] --> this opens an interactive repl.
taiko <js file> [option]  --> executes the js script.
```

There seems to be an issue related to unknown flags. When we provide the `js file` argument and pass an unknown flag commander does not complain about that. But when we pass only unknown flag without arguments commander prints a nice message that provides flag was invalid.

It would be great if the commander complains about the unknown flags even if they are passed after arguments.

**Comment by negiDharmendra** [comment] 2019-02-25 11:10
In order to fix the issue, we need to pass the unknown parameter to the while emitting the `'command:*'` event on the following file. 
https://github.com/tj/commander.js/blob/68545af7130967bc1a35ae30e9567d78c5e56d8a/index.js#L656

**Comment by shadowspawn** [comment] 2019-03-27 07:11
Have you got a small example program?

(I do see the warning for unknown flags in my program which has subcommands, but looks like you have just an optional argument and options and no subcommands?)

**Comment by clarsen** [comment] 2019-05-23 17:52
Attached is a PR that does the suggested behavior and adjustment of tests.  I'm a little hesitant about it though because it breaks the existing default behavior of ignoring unknown options, instead resulting in an error.

While this is the desired behavior for my programs, others might be relying on the silent default handling of unknown options.

**Comment by shadowspawn** [comment] 2019-07-27 01:52
I have reproduced this, and realised it is a duplicate of #561. Closing in favour of that open issue.

Thank you  for your contributions.

**Closed** 2019-07-31 03:21 UTC

**Comment by shadowspawn** [comment] 2019-08-17 05:55
After deeper analysis I discovered that there are different behaviours depending on whether there is an action handler attached to the program. #965 is targeting the case when there is an action handler, and original report in #561 covering no action handler. Not sure which case applies to `taiko` but have an open PR and an open issue to cover the two possibilities, so will still leave this closed.
