### ISSUE TITLE
alias doesn't work with git-style commands

### ISSUE THREAD

**Issue by thoughtless** [tj/commander.js#419] opened 2015-07-03 07:37 UTC
Using alias with git-style commands like this doesn't work:

```
var program = require('commander');
program
  .version('0.0.1')
  .command('list', 'list some cool stuff')
  .alias('ls')
  .parse(process.argv);
```

Ideally I could just have `pm` and `pm-list` and the above would cause `./pm ls` to invoke `pm-list`.

**Comment by justinhelmer** [comment] 2016-01-27 18:59
This would be huge. These sub-commands are getting more and more popular.

+1

**Comment by datatypevoid** [comment] 2016-03-19 18:50
+1 

This would be a really nice addition.

**Comment by rstoenescu** [comment] 2016-08-06 14:38
+1
Have been looking for this but found no solution. This would be a great addition.

**Comment by hedgerh** [comment] 2016-09-02 01:46
For anyone wondering,

This has apparently been fixed and merged into master, but not published to npm yet.

I'm pointing my dependency to the repo until the next release:
```
"commander": "git+https://github.com/tj/commander.js.git"
```

**Comment by mbilbille** [comment] 2017-04-20 08:17
+1
Yes @hedgerh solution works, but it would be nice to ship this in a new release :)
Any update? Sad... this project is almost dead, no release since October 2015.

**Comment by luqimin** [comment] 2017-10-21 13:42
any update?

**Comment by shadowspawn** [comment] 2019-05-20 11:00
I was not able to reproduce this. (Hopefully fixed!)

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Closed by shadowspawn** 2019-05-20 11:00 UTC
