### ISSUE TITLE
.action is broken; README gives incorrect instructions for .action

### ISSUE THREAD

**Issue by StoneCypher** [tj/commander.js#331] opened 2015-01-16 19:07 UTC
There are instructions for `.action` in the README.  Those instructions are incorrect.  If you copy pasta the example code, your instance will fail a la #285.

However, if you imitate [the test](https://github.com/tj/commander.js/blob/master/test/test.command.action.js) and add both a `.command` and a `.option` first, the app can run - with incorrect results.

Given the code

``` javascript
var Commander = require("commander"),

    Package   = require("./package.json"),
    lib       = path.join( path.dirname( fs.realpathSync(__filename) ), "rlode.js" );

Commander
    .version(Package.version)
    .command('rlode [options] <glob ...>')
    .option('-g, --glob', 'specify glob to match against')
    .action(function(cmd, opts) {
        console.log(JSON.stringify([ "finder", cmd, opts ]));
    });

Commander.parse(process.argv);
```

No apparent command will actually trigger that action, however, and neither `-g` nor `--glob` are recognized.

```
Johns-MacBook-Pro:ReverseLodestone johnh$ rlode
[]
Johns-MacBook-Pro:ReverseLodestone johnh$ rlode myglob
[]
Johns-MacBook-Pro:ReverseLodestone johnh$ rlode -g myglob

  error: unknown option `-g'

Johns-MacBook-Pro:ReverseLodestone johnh$ rlode --glob myglob

  error: unknown option `--glob'
```

Also, the help text is badly broken.  `[options]` occurs twice, `<glob ...>` is incorrectly trimmed, and there's a stray `undefined` at the end.

```
Johns-MacBook-Pro:ReverseLodestone johnh$ rlode --help

  Usage: rlode [options] [command]


  Commands:

    rlode [options] [options] <glo>  undefined

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

It is not clear whether this requirement is intentional.  I recommend against this requirement; it is unnecessary and cumbersome.

**Comment by SomeKittens** [comment] 2015-01-16 23:00
Closing as dupe of #285 - you should comment there if you've got more.

**Comment by StoneCypher** [comment] 2015-01-16 23:25
@SomeKittens I did comment there before I opened this, and this is not a dupe of #285.

Please re-open.

**Comment by zhiyelee** [comment] 2015-01-17 19:31
@StoneCypher 

In your example, `-g` is an option belong to the  `rlode` __sub-command__ instead of the main command.

```js
#!/usr/bin/env node
var Commander = require("./");


Commander
    .version('0.1.0')
    .command('rlode [options] <glob ...>')
    .option('-g, --glob', 'specify glob to match against')
    .action(function(cmd, opts) {
        console.log('action triggered');
    });

Commander.parse(process.argv);
```
```js
✍ ./t.js -h

  Usage: t [options] [command]


  Commands:

    rlode [options] [options] <glo>  undefined

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

```js
✍ ./t.js rlode -h

  Usage: rlode [options] [options] <glo>

  Options:

    -h, --help  output usage information
    -g, --glob  specify glob to match against
```

**Comment by zhiyelee** [comment] 2015-01-17 19:37
I will have a look at the twice `[options]` and the `undefined`, thanks a lot.

**Comment by StoneCypher** [comment] 2015-01-18 10:00
Thank you for re-opening.

**Comment by shadowspawn** [comment] 2019-03-20 10:20
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Closed by shadowspawn** 2019-03-20 10:20 UTC

**Comment by StoneCypher** [comment] 2019-04-03 02:18
I have never understood a library's culture of shutting down suggestions just because nobody's handled them yet

**Comment by shadowspawn** [comment] 2019-04-03 04:54
People have different personal preferences about how to handle old issues. Libraries have different policies and practices about old issues.

Before I started closing some of the old issues, I looked around a bit to see what other projects do. I like this short commentary from a popular automated approach:
https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea

I also like this quote from Steve Jobs: 

> People think focus means saying yes to the thing you've got to focus on. But that's not what it means at all. It means saying no to the hundred other good ideas that there are. You have to pick carefully. I'm actually as proud of the things we haven't done as the things I have done. Innovation is saying no to 1,000 things.

**Comment by StoneCypher** [comment] 2019-04-04 21:04
I guess I have a different viewpoint.

To me, it seems like throwing away knowledge in the hope of a false feeling of "cleanliness."

The defect remains; it is merely no longer known

**Comment by StoneCypher** [comment] 2019-04-04 21:04
Anyway, your library; do as you will

**Comment by shadowspawn** [comment] 2019-11-08 22:39
I was rereading this issue and noticed the likely problem. You are defining a (sub) command with the name of your parent command.

Given you are calling the program like:
```
rlode --glob myglob
```

You probably want to delete this line
```
    .command('rlode [options] <glob ...>')
```

And you can specify more about how the "program" is expected to called with `.arguments()` or '.usage()`.
