### ISSUE TITLE
Undocumented behavior change since 2.x

### ISSUE THREAD

**Issue by guimard** [tj/commander.js#1203] opened 2020-02-26 21:13 UTC
Hi,

this simple program has 2 different behavior depending on commander version:
```javascript
var p = require('commander');
p.option('-d, --debug [level]', 'debug level')
 .option('-m, --mangle [test]', 'mangle')
 .option('--out', 'output')
 
p.parse(process.argv);
console.error('Debug args:', p.opts());
```

Resuilt of `node test.js -dm --out`:
 * 2.x : `Debug args: { debug: true, mangle: true, out: true }`
 * 4.x : `Debug args: { debug: 'm', mangle: undefined, out: true }`

This has strange effect when using uglify-js.

Cheers,
Xavier

**Comment by shadowspawn** [comment] 2020-02-26 22:58
Quick response: I think this is due to changes from #395, released in Commander 3.0.0

https://github.com/tj/commander.js/releases/tag/v3.0.0

**Comment by shadowspawn** [comment] 2020-02-27 05:02
The implementation of option parsing is refined further in Commander v5, and the updated README description is:

> Multiple short flags may optionally be combined in a single argument following the dash: boolean flags, the last flag may take a value, and the value. For example -a -b -p 80 may be written as -ab -p80 or even -abp80.

**Comment by guimard** [comment] 2020-03-03 15:37
Hi,

commander 5.0.0-4 fixes the problem.

Cheers,
Xavier

**Comment by guimard** [comment] 2020-03-03 17:26
Following the doc:
> Multiple short flags may optionally be combined in a single argument following the dash: boolean flags, the last flag may take a value, and the value. For example -a -b -p 80 may be written as -ab -p80 or even -abp80.

It becomes a bug

**Comment by shadowspawn** [comment] 2020-03-03 19:33
Drat, the new wording is not as clear as I hoped! The behaviour is as intended, but I will recheck the source documentation for behaviour and wording of description.

**Comment by shadowspawn** [comment] 2020-03-03 23:16
The standard I consult is: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

Commander is more flexible with optional values than described there, but Commander is deliberately supporting the pattern that a value can directly follow the short flag, from item 2:

> If the SYNOPSIS shows an optional option-argument (as with [ -f[ option_argument]] in the example), a conforming application shall place any option-argument for that option directly adjacent to the option in the same argument string, without intervening <blank> characters.

And Guideline 5: 

> One or more options without option-arguments, followed by at most one option that takes an option-argument, should be accepted when grouped behind one '-' delimiter.

**Comment by shadowspawn** [comment] 2020-04-01 22:47
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

Thank you  for your contributions.

**Closed by shadowspawn** 2020-04-01 22:47 UTC

**Comment by shadowspawn** [comment] 2020-08-08 10:13
I think this behaviour change will be a problem for heavy users of optional values when they upgrade Commander, even though it is deliberate. Opened a PR to make it configurable.
