### ISSUE TITLE
Make commander based npm packages compatible with homebrew install

### ISSUE THREAD

**Issue by daften** [tj/commander.js#866] opened 2018-09-18 08:53 UTC
I think this is an issue for this package. I mentioned some details here: https://github.com/Homebrew/homebrew-core/pull/32154#pullrequestreview-155949702

I try to create a homebrew Formula to install gitlab-time-tracker, however, after installation it doesn't work. It seems this package isn't able to determine the actual folder to use correctly. Maybe the symlinks should be followed in a loop to find the actual src folder (if that's possible)?

With the Formula install:

```
$ gtt config
baseDir:/usr/local/Cellar/gitlab-time-tracker/1.7.27/bin
gtt-config(1) does not exist, try --help
```

With npm install -g:

```
$ gtt config
baseDir:/usr/local/lib/node_modules/gitlab-time-tracker/src
```

**Comment by jd20** [comment] 2018-10-01 19:28
This seems like an issue for yarn on Ubuntu as well, when installing with `yarn global add`, I'm seeing two levels of symlinks, which throws off commander. I tried installing gitlab-time-tracker on Ubuntu just to make sure it wasn't my own package's problem, and I'm seeing the same error, so not just a Homebrew issue. I'm running yarn 1.10 on Ubuntu 18.

Agree that the sensible fix would be to follow the symlink recursively, to some sane limit. I made a recent fix to that code, so I'll try to put together a PR and test case soon.

**Comment by jd20** [comment] 2018-10-10 20:39
Dupe of #869.

**Comment by daften** [comment] 2018-10-10 22:13
Not a dupe, this is an issue, the other is a PR. :)

**Comment by jd20** [comment] 2018-10-10 22:14
Yes, I spoke too soon... it is a PR that would fix this issue though 👍

**Comment by shadowspawn** [comment] 2019-04-03 08:12
This may have been fixed in: https://github.com/tj/commander.js/releases/tag/v2.20.0

**Comment by shadowspawn** [comment] 2019-05-30 08:06
No activity on this one for a month, and hopefully fixed. Fingers crossed. Closing.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2019-05-30 08:06 UTC

**Comment by daften** [comment] 2020-06-11 00:10
Extremely late, but this is indeed properly fixed. Thanks!
