### ISSUE TITLE
Default command does not parse flags

### ISSUE THREAD

**Issue by tandrewnichols** [tj/commander.js#463] opened 2015-10-29 14:11 UTC
I have a feeling this may be an open issue somewhere, but I was unable to find it. I apologize if it is.

If you use a default command (e.g. `.command('*')`), options are not parsed for this command. So for example:

``` js
program
  .command('*')
  .option('-c, --count [count]', 'Do this [count] times')
  .action(function(arg, options) {
    console.log(options);
  });
```

The logged options object looks like it always does in a command _except_, if you pass `-c` or `--count`, options.count is undefined.

**Comment by tandrewnichols** [comment] 2015-10-29 14:13
Ah, if you put the option _before_ the command, it does work. That's totally acceptable though possibly counter-intuitive. I'll leave this open for now in case you agree and want to make it work the other way around too, but feel free to close if not.

**Comment by mfowlewebs** [comment] 2015-11-12 22:14
Looks like a dupe of #461 I think? Nice workaround.

**Comment by tandrewnichols** [comment] 2015-11-13 12:12
Yeah, probably caused by the same bug.

**Comment by shadowspawn** [comment] 2019-03-18 07:39
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Closed by shadowspawn** 2019-03-18 07:39 UTC
