### ISSUE TITLE
Unable to build a automatic test tool that tests the commander Js's command action with a return value.

### ISSUE THREAD

**Issue by PreethiVuchuru27916** [tj/commander.js#1849] opened 2023-02-24 20:30 UTC
I have a file fele.js that specifies all commands that my app needs.

Command Used - Just says hello world when hello is entered.
```javascriptconst program = new commander.Command();
const helloCommand = program.command('hello');
helloCommand
    .action(async(options) => {
       console.log("Hello World"); //Works well as 
        return "Hello World";//But this does not work. 
    })```
Now I am using Mocha to test the command. PFB Code

```javascriptconst assert = require('assert');
const { spawn } = require('child_process');
const path = require('path');

describe('Hello Command', function() {
  it('should output a greeting message', function(done) {
    const expectedOutput = 'Hello World\n';
    const cliPath = path.join(__dirname,'fele.js'); 
    const process = spawn('node', [cliPath, 'hello']);
    let actual = '';
    process.stdout.on('data', data => {
      actual += data.toString();
    });
    process.on('close', () => {
      assert.strictEqual(output, expectedOutput);
      done();
    });
  });
});```

Please do suggest me what can I do so that I get the return value from the command's action be available to the test file. 

I understand that the result can be stored in another variable and exported but I want to get a better solution. Please assist me if there is any other way.

**Comment by shadowspawn** [comment] 2023-02-24 20:48
There is not support in Commander for action handlers returning a value. See #1776 for some discussion.

One way of testing the output of your program, without needing to spawn the command, is to intercept the output. Commander does this in some of its tests: https://github.com/tj/commander.js/blob/master/tests/command.addHelpText.test.js

**Comment by PreethiVuchuru27916** [comment] 2023-02-24 21:24
Thanks for clarification.

However the approach you specified again works only for console.log output that the process.stdout can read from? Then to test a commander's command is to test what shows up in the console? Would that be a good way for testing?

**Comment by shadowspawn** [comment] 2023-02-24 21:39
An approach I have used is to test the internal implementation of the program directly, and separately test the command-line parsing. I have the action handler call a routine to do the work with the parsed input, and mocked the call so I can just test the CLI parsing was working as intended. I have the whole command-line parsing available as a routine so I can use it repeatedly in tests.

https://github.com/shadowspawn/forest-arborist/blob/main/tests/command.unit.test.ts

**Comment by shadowspawn** [comment] 2023-03-23 19:36
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Closed by shadowspawn** 2023-03-23 19:36 UTC
