### ISSUE TITLE
*Bug* When specify none-defined options followed by values don't exit program with error

### ISSUE THREAD

**Issue by snowman** [tj/commander.js#1039] opened 2019-09-08 09:46 UTC
```js
// File: index.js
const program = require('commander');

program
  .version('0.0.1')
  .parse(process.argv);

const args = program.args;

console.log(args);
```

```bash
$ node index.js --bug
error: unknown option '--bug'

$ node index.js --bug 0
error: unknown option '--bug'

$ node index.js --bug 0 1 2 3
[ '1', '2', '3' ]
```

dependency:
```json
$ cat package.json
{
  "dependencies": {
    "commander": "^3.0.1"
  }
}
```

Expecting exit code with an error instead of continue of it.

**Comment by shadowspawn** [comment] 2019-09-08 11:30
Reproduced.

**Comment by shadowspawn** [comment] 2019-09-14 23:40
This old PR looks like same issue: #121

**Comment by shadowspawn** [comment] 2019-09-17 09:21
Likely to be same issue as #561

**Comment by shadowspawn** [comment] 2019-11-09 08:23
Closing this as duplicate of #561

**Closed by shadowspawn** 2019-11-09 08:23 UTC
Labels: bug

**Comment by shadowspawn** [comment] 2020-01-07 03:06
Opened a PR to rework option parsing to avoid dropping options and arguments: #1138
